"""initial

Revision ID: 15a5faf78b3d
Revises: 
Create Date: 2026-06-02 18:29:56.393948
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '15a5faf78b3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('markers', 'region_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('markers', 'category_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('users', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('markers', 'category_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('markers', 'region_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
