"""add_marker_status_and_submitted_by

Revision ID: 5a96609e0725
Revises: 15a5faf78b3d
Create Date: 2026-06-08 10:47:40.736633
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5a96609e0725'
down_revision: Union[str, None] = '15a5faf78b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('markers', sa.Column('submitted_by', sa.Integer(), nullable=True))
    op.create_index('ix_markers_map_name', 'markers', ['map_name'], unique=False)
    op.create_index('ix_markers_region_map_category', 'markers', ['region_id', 'map_name', 'category_id'], unique=False)
    op.create_index('ix_markers_status', 'markers', ['status'], unique=False)
    op.create_foreign_key(None, 'markers', 'users', ['submitted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'markers', type_='foreignkey')
    op.drop_index('ix_markers_status', table_name='markers')
    op.drop_index('ix_markers_region_map_category', table_name='markers')
    op.drop_index('ix_markers_map_name', table_name='markers')
    op.drop_column('markers', 'submitted_by')
    op.drop_column('markers', 'status')
    # ### end Alembic commands ###
