"""drop_unused_columns

Revision ID: fc9073b0595d
Revises: 5a96609e0725
Create Date: 2026-06-08 15:14:09.863994
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'fc9073b0595d'
down_revision: Union[str, None] = '5a96609e0725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'color')
    op.drop_column('regions', 'tile_url')
    op.alter_column('users', 'is_admin',
               existing_type=mysql.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('users', 'is_admin',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.add_column('regions', sa.Column('tile_url', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('categories', sa.Column('color', mysql.VARCHAR(length=7), nullable=True))
    # ### end Alembic commands ###
